# Created by nibo at 2015-06-02
Feature: Internal
  Internal functions for Optimal Framework

  Scenario: A local _id needs to be generated using an environment _id
    Then the correct value should be generated by node_id_with_env


  Scenario: Handling unimplemented class methods
    Given a class has and unimplemented method
    Then an error should be raised calling that method